version: '3.4'

networks:
  backend:

services:
  pluxee.customerservice:
    container_name: pluxee-customerservice
    image: ${DOCKER_REGISTRY-}pluxeecustomerservice
    build:
      context: .
      dockerfile: src/CustomerService/Pluxee.CustomerService/Dockerfile
    networks:
      - backend
    depends_on:
      - pluxee.customerservice.db
      - pluxee.rabbitmq

  pluxee.orderservice:
    container_name: pluxee-orderservice
    image: ${DOCKER_REGISTRY-}pluxeeorderservice
    build:
      context: .
      dockerfile: src/OrderService/Pluxee.OrderService/Dockerfile
    networks:
      - backend
    depends_on:
      - pluxee.orderservice.db
      - pluxee.rabbitmq

  pluxee.paymentservice:
    container_name: pluxee-paymentservice
    image: ${DOCKER_REGISTRY-}pluxeepaymentservice
    build:
      context: .
      dockerfile: src/PaymentService/Pluxee.PaymentService/Dockerfile
    networks:
      - backend
    depends_on:
      - pluxee.paymentservice.db
      - pluxee.rabbitmq

  pluxee.productservice:
    container_name: pluxee-productservice
    image: ${DOCKER_REGISTRY-}pluxeeproductservice
    build:
      context: .
      dockerfile: src/ProductService/Pluxee.ProductService/Dockerfile
    networks:
      - backend
    depends_on:
      - pluxee.productservice.db
      - pluxee.rabbitmq

  pluxee.customerservice.db:
    image: postgres:latest
    container_name: pluxee-customerservice-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - pluxee-customerservice-db-data:/var/lib/postgresql/data
    networks:
      - backend

  pluxee.orderservice.db:
    image: postgres:latest
    container_name: pluxee-orderservice-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - pluxee-orderservice-db-data:/var/lib/postgresql/data
    networks:
      - backend

  pluxee.paymentservice.db:
    image: postgres:latest
    container_name: pluxee-paymentservice-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - pluxee-paymentservice-db-data:/var/lib/postgresql/data
    networks:
      - backend

  pluxee.productservice.db:
    image: postgres:latest
    container_name: pluxee-productservice-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - pluxee-productservice-db-data:/var/lib/postgresql/data
    networks:
      - backend

  pluxee.rabbitmq:
    image: rabbitmq:3-management
    container_name: pluxee-rabbitmq
    hostname: rabbitmq
    restart: always
    volumes:
      - pluxee-rabbitmq-data:/var/lib/rabbitmq/
      - pluxee-rabbitmq-log:/var/log/rabbitmq
    networks:
      - backend

volumes:
  pluxee-customerservice-db-data:
  pluxee-orderservice-db-data:
  pluxee-paymentservice-db-data:
  pluxee-productservice-db-data:
  pluxee-rabbitmq-data:
  pluxee-rabbitmq-log: