version: '3.4'

networks:
  backend:

services:
  pluxee.customerservice:
    container_name: pluxee-customerservice
    image: ${DOCKER_REGISTRY-}pluxeecustomerservice
    build:
      context: .
      dockerfile: src/CustomerService/Pluxee.CustomerService/Dockerfile
    networks:
      - backend

  pluxee.orderservice:
    container_name: pluxee-orderservice
    image: ${DOCKER_REGISTRY-}pluxeeorderservice
    build:
      context: .
      dockerfile: src/OrderService/Pluxee.OrderService/Dockerfile
    networks:
      - backend

  pluxee.paymentservice:
    container_name: pluxee-paymentservice
    image: ${DOCKER_REGISTRY-}pluxeepaymentservice
    build:
      context: .
      dockerfile: src/PaymentService/Pluxee.PaymentService/Dockerfile
    networks:
      - backend

  pluxee.productservice:
    container_name: pluxee-productservice
    image: ${DOCKER_REGISTRY-}pluxeeproductservice
    build:
      context: .
      dockerfile: src/ProductService/Pluxee.ProductService/Dockerfile
    networks:
      - backend