version: '3.4'

services:
  pluxee.customerservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "61001:8080"

  pluxee.orderservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "61002:8080"

